//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftEcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountInvoice()
        {
            this.AccountInvoiceDetails = new HashSet<AccountInvoiceDetail>();
        }
    
        public string ID { get; set; }
        public string MyCustomer { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Bill { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<int> Posted { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<int> Paid { get; set; }
        public string PaidBy { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string Ref { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string EnableNotification { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public int myserial { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> WHT { get; set; }
        public Nullable<decimal> POSCharges { get; set; }
        public Nullable<int> PrestigeID { get; set; }
        public string Notes { get; set; }
        public string StaffID { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusNote { get; set; }
        public string StatusResponseNote { get; set; }
        public Nullable<int> PostStatus { get; set; }
        public Nullable<int> DiscountPosted { get; set; }
        public Nullable<int> HoldStatus { get; set; }
        public string HUsername { get; set; }
        public string TransferStoreID { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string Address { get; set; }
        public string BType { get; set; }
        public Nullable<System.TimeSpan> Timed { get; set; }
        public string Remarks { get; set; }
        public string FIRSIRN { get; set; }
        public string FIRSIRNStatus { get; set; }
        public Nullable<System.DateTime> FIRSIRNGeneratedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountInvoiceDetail> AccountInvoiceDetails { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
