//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftEcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInvoiceDetail
    {
        public string ID { get; set; }
        public Nullable<decimal> Units { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string MyInvoice { get; set; }
        public string Notes { get; set; }
        public string Username { get; set; }
        public Nullable<int> Posted { get; set; }
        public string ProductID { get; set; }
        public Nullable<decimal> QtyPosted { get; set; }
        public Nullable<decimal> QtyLeft { get; set; }
        public Nullable<int> PrestigeID { get; set; }
        public string SN { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public int myserial { get; set; }
        public string WarehouseID { get; set; }
        public Nullable<int> Promo { get; set; }
        public Nullable<decimal> DiscountID { get; set; }
        public Nullable<decimal> ShadowQty { get; set; }
        public Nullable<decimal> VAT { get; set; }
    
        public virtual AccountInvoice AccountInvoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
