//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftEcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public string ID { get; set; }
        public string ServiceID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CompanyID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Status { get; set; }
        public string OrderID { get; set; }
        public string UserID { get; set; }
        public string adminSubscriptionPlanID { get; set; }
        public string MMYY { get; set; }
        public string SubType { get; set; }
        public Nullable<decimal> DRate { get; set; }
        public string Currency { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
