//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftEcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Carts = new HashSet<Cart>();
            this.Stores = new HashSet<Store>();
        }
    
        public string ID { get; set; }
        public string CompanyName { get; set; }
        public string ContactAddress { get; set; }
        public string PostalAddress { get; set; }
        public string WebsiteAddress { get; set; }
        public string EmailAddress { get; set; }
        public string CompanyMotto { get; set; }
        public string PhoneNumber { get; set; }
        public string CompanyLogo { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string UserId { get; set; }
        public string SubscriptionID { get; set; }
        public string IDCardID { get; set; }
        public string CCardID { get; set; }
        public string InvoiceID { get; set; }
        public string ReceiptID { get; set; }
        public string PayrollID { get; set; }
        public string StaffUploadID { get; set; }
        public string PictureUploadID { get; set; }
        public string DocumentUploadID { get; set; }
        public string AppointmentLetterID { get; set; }
        public string PromotionLetter { get; set; }
        public string BackDesignation { get; set; }
        public string BackText { get; set; }
        public string FrontHeader { get; set; }
        public string BackHeader { get; set; }
        public string LetterHeadID { get; set; }
        public string Services { get; set; }
        public Nullable<int> Category { get; set; }
        public string Address2 { get; set; }
        public string ProfileStatus { get; set; }
        public string TaxType { get; set; }
        public Nullable<double> Taxvalue { get; set; }
        public string ReferalCode { get; set; }
        public string AccountsID { get; set; }
        public string SMSSubAccount { get; set; }
        public int Serial { get; set; }
        public string Description { get; set; }
        public string ReferredBy { get; set; }
        public Nullable<bool> IntroductionStatus { get; set; }
        public Nullable<bool> CompanyInfoStatus { get; set; }
        public Nullable<bool> AccountSetupStatus { get; set; }
        public Nullable<bool> MenuSetupStatus { get; set; }
        public string ReturnUrl { get; set; }
        public Nullable<int> RemoveBranding { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store> Stores { get; set; }
    }
}
