//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftEcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.AccountInvoices = new HashSet<AccountInvoice>();
            this.CustomerPayments = new HashSet<CustomerPayment>();
        }
    
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string MyStore { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AcquiredBy { get; set; }
        public Nullable<decimal> StartingBalance { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string AcquisitionMode { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<int> PrestigeID { get; set; }
        public Nullable<int> CustomerType { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> TotalBalance { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Address2 { get; set; }
        public string PrefferedAddress { get; set; }
        public string PrefferedState { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string Bank { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<decimal> MinBalance { get; set; }
        public Nullable<System.DateTime> PurgedDate { get; set; }
        public Nullable<int> PurgeStatus { get; set; }
        public Nullable<decimal> MyContribution { get; set; }
        public Nullable<int> RefundStatus { get; set; }
        public Nullable<System.DateTime> RegAmountPaidDate { get; set; }
        public Nullable<decimal> RegAmount { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> RegFeeStatus { get; set; }
        public string CustomerNumber { get; set; }
        public string Sex { get; set; }
        public string NextOfKin { get; set; }
        public string NextOfKinAddress { get; set; }
        public string NextOfKinPhone { get; set; }
        public string NextOfKinRelationship { get; set; }
        public string Employer { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> EmploymentDate { get; set; }
        public Nullable<System.DateTime> RetirementDate { get; set; }
        public string EmployeeNumber { get; set; }
        public string EnableMinBalance { get; set; }
        public Nullable<decimal> LedgerBalance { get; set; }
        public int SerialNumber { get; set; }
        public string DirectCode { get; set; }
        public string PartnerPlan { get; set; }
        public string PayStackBankCode { get; set; }
        public string FlutterwaveBankCode { get; set; }
        public string PayStackAccountNumber { get; set; }
        public string FlutterwaveAccountNumber { get; set; }
        public string BVN { get; set; }
        public string NIN { get; set; }
        public string FamilyMember1Name { get; set; }
        public string FamilyMember1Relationship { get; set; }
        public string FamilyMember1DOB { get; set; }
        public string FamilyMember1Age { get; set; }
        public string FamilyMember1Occupation { get; set; }
        public string FamilyMember2Name { get; set; }
        public string FamilyMember2Relationship { get; set; }
        public string FamilyMember2DOB { get; set; }
        public string FamilyMember2Age { get; set; }
        public string FamilyMember2Occupation { get; set; }
        public string FamilyMember3Name { get; set; }
        public string FamilyMember3Relationship { get; set; }
        public string FamilyMember3DOB { get; set; }
        public string FamilyMember3Age { get; set; }
        public string FamilyMember3Occupation { get; set; }
        public string FamilyMember4Name { get; set; }
        public string FamilyMember4Relationship { get; set; }
        public string FamilyMember4DOB { get; set; }
        public string FamilyMember4Age { get; set; }
        public string FamilyMember4Occupation { get; set; }
        public string Profession { get; set; }
        public string Designation { get; set; }
        public string OtherClubDetails { get; set; }
        public string MaritalStatus { get; set; }
        public string Ref1Name { get; set; }
        public string Ref1Address { get; set; }
        public string Ref1PhoneNo { get; set; }
        public string Ref1Email { get; set; }
        public string Ref1Office { get; set; }
        public string Ref2Name { get; set; }
        public string Ref2Address { get; set; }
        public string Ref2PhoneNo { get; set; }
        public string Ref2Email { get; set; }
        public string Ref2Office { get; set; }
        public string Nationality { get; set; }
        public string IDType { get; set; }
        public string IDNumber { get; set; }
        public string IDExpiryDate { get; set; }
        public Nullable<int> Unit { get; set; }
        public string Phone2 { get; set; }
        public Nullable<System.Guid> SessionToken { get; set; }
        public Nullable<System.DateTime> TrialStartDate { get; set; }
        public Nullable<bool> IsTrialExpired { get; set; }
        public string ResetTokenHash { get; set; }
        public Nullable<System.DateTime> ResetTokenExpiry { get; set; }
        public string OfficialEmail { get; set; }
        public string OfficeAddress { get; set; }
        public Nullable<decimal> MonthlySalary { get; set; }
        public string RefOfficeAddress { get; set; }
        public string RefPhone2 { get; set; }
        public string RefRelationship { get; set; }
        public Nullable<decimal> RefMonthlyNetPay { get; set; }
        public string RefBVN { get; set; }
        public string RefId { get; set; }
        public string NextOfKinOfficeAddress { get; set; }
        public string PhotoPath { get; set; }
        public string BankStateDocId { get; set; }
        public string CustomerIdCardId { get; set; }
        public string UtilityBillId { get; set; }
        public string EmployLetterId { get; set; }
        public string NextOfKinPhone2 { get; set; }
        public Nullable<int> KYCLevelId { get; set; }
        public string KYCStatus { get; set; }
        public Nullable<bool> IsKYCVerified { get; set; }
        public Nullable<bool> NINVerified { get; set; }
        public string NINStatus { get; set; }
        public Nullable<bool> IsBusiness { get; set; }
        public string RCNumber { get; set; }
        public string BusinessName { get; set; }
        public Nullable<bool> KYBVerified { get; set; }
        public string KYBStatus { get; set; }
        public string RefKYCStatus { get; set; }
        public bool RefIsKYCVerified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountInvoice> AccountInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPayment> CustomerPayments { get; set; }
        public virtual Store Store { get; set; }
    }
}
