//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftEcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPayment
    {
        public string ID { get; set; }
        public string MyInvoice { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Method { get; set; }
        public string Particulars { get; set; }
        public string PaidBy { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Ref { get; set; }
        public string EnableNotification { get; set; }
        public string CustomerID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public int myserial { get; set; }
        public Nullable<int> PrestigeID { get; set; }
        public string EnteredBy { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<int> Post { get; set; }
        public Nullable<int> PaidStatus { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string TransactionReference { get; set; }
        public string ProviderName { get; set; }
        public Nullable<System.TimeSpan> Timed { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
