//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftEcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSetting
    {
        public string ID { get; set; }
        public string StoreID { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string IMAPServer { get; set; }
        public Nullable<int> IMAPPort { get; set; }
        public string SMTPServer { get; set; }
        public Nullable<int> SMTPPort { get; set; }
        public Nullable<bool> UseSSL { get; set; }
        public Nullable<System.DateTime> LastCheckedDate { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> Status { get; set; }
        public string AIPrompt { get; set; }
        public string AIReply { get; set; }
        public string StaffID { get; set; }
        public string AIResource { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
