//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftEcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementCategoryVendor
    {
        public string ID { get; set; }
        public string CategoryID { get; set; }
        public string SupplierID { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ProcurementCategory ProcurementCategory { get; set; }
    }
}
