//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftEcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.AccountInvoiceDetails = new HashSet<AccountInvoiceDetail>();
            this.ProductImages = new HashSet<ProductImage>();
            this.ProductVariants = new HashSet<ProductVariant>();
            this.ShoppingCartDetails = new HashSet<ShoppingCartDetail>();
        }
    
        public string ID { get; set; }
        public string Product1 { get; set; }
        public Nullable<decimal> ReOrderLevel { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate2 { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Units { get; set; }
        public Nullable<decimal> StartingStock { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<decimal> WholesalePrice { get; set; }
        public Nullable<decimal> SellingBPrice { get; set; }
        public Nullable<decimal> SellingCPrice { get; set; }
        public string IsVatable { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<decimal> TotalPurchases { get; set; }
        public Nullable<decimal> TotalSales { get; set; }
        public string BarCode { get; set; }
        public string LargeImage { get; set; }
        public string SmallImage { get; set; }
        public string CalculateStock { get; set; }
        public string MyStore { get; set; }
        public Nullable<decimal> StockLevel { get; set; }
        public string Category { get; set; }
        public string IsInventory { get; set; }
        public string Status { get; set; }
        public string Negotiable { get; set; }
        public string Description { get; set; }
        public Nullable<int> AdCategoryID { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> OnlineRate { get; set; }
        public string AllowDirectPayment { get; set; }
        public string Features { get; set; }
        public string SalesAccount { get; set; }
        public string PurchaseAccount { get; set; }
        public string InventoryAccount { get; set; }
        public string PrimaryProduct { get; set; }
        public Nullable<decimal> Conversion { get; set; }
        public string ConversionType { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<int> PrestigeID { get; set; }
        public Nullable<decimal> Reserve { get; set; }
        public string HasSerial { get; set; }
        public string DefaultRate { get; set; }
        public Nullable<decimal> WholeSaleQty { get; set; }
        public Nullable<decimal> ProductionSetupQty { get; set; }
        public Nullable<decimal> MaximumStock { get; set; }
        public Nullable<decimal> LastPurchase { get; set; }
        public Nullable<decimal> LastPurchasePrice { get; set; }
        public Nullable<decimal> StockLevelPlusWarehouses { get; set; }
        public string ShelfNo { get; set; }
        public string PriceIncludesVAT { get; set; }
        public Nullable<decimal> PercentOff { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public int SerialNumber { get; set; }
        public string Recurring { get; set; }
        public Nullable<decimal> ProductionDefaultQty { get; set; }
        public Nullable<decimal> ProductionWeightConversion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountInvoiceDetail> AccountInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariant> ProductVariants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCartDetail> ShoppingCartDetails { get; set; }
    }
}
