//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftEcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public string ID { get; set; }
        public string MyCompany { get; set; }
        public string Category { get; set; }
        public string ForSale { get; set; }
        public string MasterID { get; set; }
        public Nullable<System.TimeSpan> Timed { get; set; }
    
        public virtual ProductCategoryMaster ProductCategoryMaster { get; set; }
    }
}
