//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftEcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariant
    {
        public string ID { get; set; }
        public string Attribute { get; set; }
        public string Value { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Status { get; set; }
        public string Code { get; set; }
        public string ProductID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> TotalSales { get; set; }
        public Nullable<decimal> TotalPurchases { get; set; }
        public Nullable<decimal> StockLevel { get; set; }
        public Nullable<decimal> StartingStock { get; set; }
        public Nullable<decimal> OnlineRate { get; set; }
        public string SerialNo { get; set; }
        public string Location { get; set; }
        public string EnteredBy { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
