//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftEcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public string ID { get; set; }
        public string ProductID { get; set; }
        public string VariantID { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
