//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftEcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.Customers = new HashSet<Customer>();
            this.MailSettings = new HashSet<MailSetting>();
        }
    
        public string ID { get; set; }
        public string StoreName { get; set; }
        public string Address { get; set; }
        public string MyCompany { get; set; }
        public string InvoicePerPage { get; set; }
        public string GuestBillPerPage { get; set; }
        public string OnlineCashAccount { get; set; }
        public Nullable<int> ExpiryDateMonthPrompt { get; set; }
        public string EditRate { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> EnableSC { get; set; }
        public Nullable<bool> EnableVAT { get; set; }
        public Nullable<bool> EnableDiscount { get; set; }
        public string SMSSender { get; set; }
        public string NotificationOptions { get; set; }
        public Nullable<bool> TieMeasurementToOrders { get; set; }
        public Nullable<bool> EnableJobOrders { get; set; }
        public Nullable<bool> EnableRooms { get; set; }
        public Nullable<bool> EnableMeasurement { get; set; }
        public Nullable<bool> EnableMessages { get; set; }
        public Nullable<bool> EnableLeads { get; set; }
        public Nullable<bool> EnableCase { get; set; }
        public Nullable<bool> EnableProperty { get; set; }
        public Nullable<bool> EnableBirthDayEmailStaff { get; set; }
        public Nullable<bool> EnableBirthDayEmailSupplier { get; set; }
        public Nullable<bool> EnableBirthDayEmailCustomer { get; set; }
        public string code { get; set; }
        public string Status { get; set; }
        public string Bank { get; set; }
        public string BankCode { get; set; }
        public string AccountNumber { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> EnableNewMonthYearEmailCustomer { get; set; }
        public Nullable<bool> EnableNewMonthYearEmailStaff { get; set; }
        public Nullable<bool> ControlCashBalances { get; set; }
        public string InvoiceHeader { get; set; }
        public string InvoiceFooter { get; set; }
        public Nullable<decimal> PercentPaidOrder { get; set; }
        public string TermsConditions { get; set; }
        public int MySerial { get; set; }
        public Nullable<System.DateTime> AccountingYearStart { get; set; }
        public Nullable<System.DateTime> AccountingYearEnd { get; set; }
        public string RequestQuoteText { get; set; }
        public Nullable<decimal> VATPercent { get; set; }
        public Nullable<decimal> WHTPercent { get; set; }
        public Nullable<System.DateTime> VATPrompt { get; set; }
        public string XY { get; set; }
        public Nullable<int> OpeningHour { get; set; }
        public Nullable<int> OpeningMin { get; set; }
        public Nullable<int> ClosingHour { get; set; }
        public Nullable<int> ClosingMin { get; set; }
        public Nullable<bool> ViewOnlyEnrolledCustomer { get; set; }
        public string PrestigeCode { get; set; }
        public string OneProductSale { get; set; }
        public string StoreType { get; set; }
        public string PaymentFooter { get; set; }
        public Nullable<bool> EnableAsset { get; set; }
        public Nullable<bool> EnableProduction { get; set; }
        public Nullable<bool> EnableSalesTarget { get; set; }
        public Nullable<bool> EnableProject { get; set; }
        public string SendEmailImail { get; set; }
        public string RoomHeader { get; set; }
        public string RoomIntro { get; set; }
        public string RoomFooter { get; set; }
        public string RoomPolicy { get; set; }
        public string ShowCart { get; set; }
        public string ShowOrder { get; set; }
        public string PV { get; set; }
        public string PVRetirement { get; set; }
        public string RequisitionStaff { get; set; }
        public Nullable<int> PVStartCount { get; set; }
        public string Description { get; set; }
        public string SalesView { get; set; }
        public Nullable<bool> EnableInvestment { get; set; }
        public string EnableCreateProduct { get; set; }
        public Nullable<int> DepreciationStartCount { get; set; }
        public string DepreciationMethod { get; set; }
        public string IncludeRef { get; set; }
        public string Currency { get; set; }
        public string ReturnUrl { get; set; }
        public Nullable<decimal> ProcessingFee { get; set; }
        public Nullable<decimal> StampDuty { get; set; }
        public string AutoCheckOut { get; set; }
        public Nullable<decimal> LegalDuty { get; set; }
        public Nullable<decimal> DevFee { get; set; }
        public string PayStackSecretKey { get; set; }
        public string FlutterWaveSecretKey { get; set; }
        public string X { get; set; }
        public string InvoiceSeed { get; set; }
        public string OrderSeed { get; set; }
        public string PaymentSeed { get; set; }
        public string SPaymentSeed { get; set; }
        public string CustomerDetails { get; set; }
        public string ExpenseSeed { get; set; }
        public string IncomeSeed { get; set; }
        public string AllowSignUp { get; set; }
        public Nullable<decimal> NewCustomerAmount { get; set; }
        public Nullable<decimal> NewSupplierAmount { get; set; }
        public string EnableSupplierSignup { get; set; }
        public string TwilioPhoneNumber { get; set; }
        public string CustomerTitle { get; set; }
        public string CustomerHeader { get; set; }
        public string SupplierTitle { get; set; }
        public string SupplierHeader { get; set; }
        public string ProductView { get; set; }
        public string ShopifyStoreDomain { get; set; }
        public string ShopifyAPIAccessToken { get; set; }
        public string ShopifyAPISecretKey { get; set; }
        public Nullable<bool> EnableRebates { get; set; }
        public Nullable<bool> EnableReferrals { get; set; }
        public Nullable<bool> EnableDocs { get; set; }
        public Nullable<bool> EnableCampaigns { get; set; }
        public Nullable<bool> EnableOthers { get; set; }
        public string TimeZoneId { get; set; }
        public string FIRSServiceID { get; set; }
        public Nullable<System.TimeSpan> BusinessDayStartTime { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailSetting> MailSettings { get; set; }
    }
}
